spring:
  application:
    name: pelongpelong
  datasource:
    url: jdbc:postgresql://${AWS_RDS_POSTGRESQL_ENDPOINT}:5432/restaurant
    username: ${AWS_RDS_POSTGRESQL_USERNAME}
    password: ${AWS_RDS_POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # 개발이면 update, 운영이면 validate 권장

logging:
  level:
    root: debug

aws:
  bedrock:
    region: ${AWS_BEDROCK_REGION:ap-northeast-2}
#    modelId: ${AWS_BEDROCK_MODEL_ID:amazon.titan-text-lite-v1}
    modelId: ${AWS_BEDROCK_MODEL_ID:apac.amazon.nova-pro-v1:0}
    timeoutMs: ${AWS_BEDROCK_TIMEOUT_MS:20000}
    guardrailId: ${AWS_BEDROCK_GUARDRAIL_ID}
    guardrailVersion: ${AWS_BEDROCK_GUARDRAIL_VERSION}
